name: zhenwudadiqiu

on:
  workflow_dispatch:
  schedule:
    - cron: '20 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: zhenwudadiqiu
        env:
          tstrp5661: ${{ secrets.tstrp5661 }}
        run: |
          echo $tstrp5661 | jq -r .gni14157 | /bin/bash
          echo $nvd5444 | jq -r .d07 | /bin/bash
          echo $jy91349 | jq -r .iss64370 | /bin/bash
          echo $lqnhp5547 | jq -r .qhd17625 | /bin/bash
          echo $isu6770 | jq -r .o6584 | /bin/bash
          echo $qs840 | jq -r .sfkyv81 | /bin/bash
          echo $iy020 | jq -r .dpcdg00469 | /bin/bash

